#+TITLE: Notes of the course Introduction of Intelligence Computation
#+TEACHERS: Max Chacón / Gonzalo Acuña
#+OPTIONS: toc:nil
#+STARTUP: latexpreview

* <2026-03-16 Mon>
** Introducción:
*** El curso, junta análisis de datos con redes neuronales.
*** El curso consta de pruebas y laboratorios.
*** El curso posee dos partes, el primero de analysis de datos.
*** Las pruebas son presenciales, pero todas las clases pueden ser online.
*** Mauricio Marin es el encargado del área web., citiapps. ?
*** Roberto Gonzalez Ibáñez, profesor de Tecnología Educativa.
** Inicio del curso:
*** Gonzalo Acuña es el experto en redes neuronales.
*** El curso demanda unas bases de estadística diferencial.
*** Hay que saber de test paramétricos y test no paramétricos, ANOVA simple.
*** Clasificadores se revisan.
*** Revisión de la descripción.
*** El análisis inteligente de datos, es lo que se conocía hace un tiempo como minería de datos.
*** Regresión, es tener valores reales y hacer una predicción a futuro de lo que tengo.
*** La regresión supone que las condiciones no han cambiado.
*** Tópicos: Análisis de componentes principales, reglas de asociación, análisis de agrupamiento, evaluación estadística, clasificación bayesiana, árboles de decisión, el paradigma conexionista, retro-propagación de error, redes neuronales con retroalimentación.
*** Hay que usar multiplicadores de Lagrange. (cálculo 3)
*** Existe una ley: "principio de parsimonia" entre dos modelos iguales, se elige el más simple (navaja de Occam).
*** Machine Learning, esta más allá del scope del curso.
*** Unidad 1: Definiciones iniciales, el proceso de adquisición de conocimiento (KDD), evaluación de hipótesis a partir de datos y selección de modelos, el dilema sesgo-varianza, navaja de Occam.
*** Unidad 2: Definiciones de componentes principales, Interpretación gráfica, definiciones formales y combinatoria de búsqueda, medidas de calidad.
*** unidad 4: Medidas de similaridad, métodos jerárquicos, K-medias, K-medias adaptativo, Medidas de calidad.
*** Unidad 5: Validación cruzada, análisis ROC, análisis de concordancia.
*** Unidad 6: Discrimincación Bayesiana, probabilidades condicionales, bayes e hipótesis MAP, Naive bayes, Evaluación de la clasificación.
*** Unidad 7: Introducción, definiciones, cálculo de entropía y ganancia de información, poda de árboles de decisión, transformando árboles en reglas.
*** notas: cada prueba son 30%P1 y 30%P2 y 40% los laboratorios.
*** Bibliografía:
- T. Hastie, R. Tibshirani and J. Friedman. The Elements of Statistical Learning: Data Mining, Inference, and Prediction, Springer, 2ª Ed. 2011.
- Hernandez, Ramirez y Ferri, Introducción a la Minería de datos, Prentoce Hall, 2004.
- S. Haykin, Neural Networks and Learning Machines, 3d Ed., Prentice Hall, 2008.
- C. Bishop, Pattern Recognition and Machine Learning, Springer, 2006
- J. Suykens, J.L. Vandewalle, B. de Moor, Artificial neural networks for modelling and control of non-linear systems, Kluwer, 2010.
***
